---

platform: linux

image_resource:
  type: docker-image
  source:
    repository: maven
    tag: latest

inputs:
  - name: sysmaster-web-git


outputs:
  - name: build-output

run:
  path:  mvn
  args: ["-f", "sysmaster-web-git/pom.xml", "package"]
